select job from emp order by job;
-- 위에서 부터 읽으면서 중복된것을 걸러내는 가장 쉬운 알고리즘 SORT

-- 함수 예제 실습 2번 5번 6번 7번 8번
SELECT ENAME, lower(ENAME) ,upper(ENAME), initcap(ENAME) FROM EMP;
SELECT ENAME, substr(ENAME,1,3), substr(ENAME,4), substr(ENAME,-3,2) FROM EMP;
SELECT ENAME, instr(ENAME,'A'), instr(ENAME,'A',2), instr(ENAME,'A',2,1) FROM EMP;
-- ? 
SELECT ENAME, rpad(ENAME,10,'*'), lpad(ENAME,10,'+') FROM EMP;
SELECT rpad(ENAME,10,' ')||' ''s JOB is '||lpad(JOB,10,' ') as JOB_list FROM EMP; 
SELECT ENAME,REPLACE(ENAME,'S','s') FROM EMP;
SELECT ENAME, concat(ENAME,JOB), ENAME||JOB FROM EMP;
SELECT ltrim(' 대한민국 '), rtrim(' 대한민국 '), trim(' 대한민국 ') FROM dual;
-- ?
SELECT trim('장' from '장발장'), ltrim('장발장','장'), rtrim('장발장','장') FROM dual;
SELECT length('abcd'), substr('abcd',2,2), length('대한민국'), substr('대한민국',2,2) FROM dual;
SELECT lengthb('abcd'), substrb('abcd',2,2), lengthb('대한민국'), substrb('대한민국',2,2) FROM dual;
SELECT length('abcd’), vsize('abcd’), length(), vsize() FROM dual;
-- ?

SELECT round(45.923,2), round(45.923,1), round(45.923,0), round(45.923), round(45.923,-1) FROM dual;
SELECT trunc(45.923,2), trunc(45.923,1), trunc(45.923,0), trunc(45.923), trunc(45.923,-1) FROM
dual;
SELECT mod(100,3), mod(100,2) FROM dual;
SELECT ENAME,SAL,SAL*0.053 as tax,round(SAL*0.053,0) as r_tax FROM EMP; 
SELECT CEIL(-45.594),CEIL(-45.294),CEIL(45.294),
ROUND(-45.594),ROUND(-45.294),ROUND(45.594) FROM DUAL; 
SELECT FLOOR(45.245),FLOOR(-45.245),FLOOR(45.545),FLOOR(-45.545) FROM DUAL;

SELECT SYSDATE, SYSDATE+7, SYSDATE-2, SYSDATE +1/24 FROM DUAL;
SELECT DEPTNO,ENAME,TRUNC(SYSDATE-HIREDATE) AS WORK_DAY FROM EMP ORDER BY DEPTNO,WORK_DAY DESC;

SELECT SYSDATE FROM DUAL;

SELECT ename,to_char(sysdate,'YYYY-MM-DD:HH24:MI:SS'),to_char(hiredate,'YYYY-MM-DD:HH24:MI:SS')
FROM emp;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
SELECT ename,sysdate,hiredate FROM emp;
SELECT SYSDATE FROM DUAL;


ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';
SELECT SYSDATE FROM DUAL;
SELECT HIREDATE FROM EMP;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';
SELECT SYSDATE FROM DUAL;
SELECT HIREDATE FROM EMP;

SELECT SYSDATE FROM DUAL;

SELECT HIREDATE,trunc(months_between(sysdate,HIREDATE)),months_between(HIREDATE,sysdate) FROM EMP;
-- 찌꺼기 제거 trunc(months_between(sysdate,HIREDATE))

SELECT sysdate, add_months(sysdate,3), add_months(sysdate,-1) FROM dual;

SELECT sysdate, last_day(sysdate), next_day(sysdate,'일요일'), next_day(sysdate,1),next_day(sysdate,2) FROM dual;

SELECT sysdate,round(sysdate+70,'YEAR'),round(sysdate,'MONTH'),round(TO_DATE('20-05-07','YY/MM/DD'),'DAY'),round(sysdate)
FROM dual;

SELECT sysdate,trunc(sysdate,'YEAR'),trunc(sysdate,'MONTH'),trunc(TO_DATE('20-05-06','YY/MM/DD'),'DAY') AS 일_반올림,trunc(sysdate)
FROM dual;
SELECT SYSDATE-125 FROM DUAL;
SELECT TO_DATE('20-05-08','YY/MM/DD') FROM DUAL;
SELECT
to_char(sysdate,'MM"월"DD"일"') as mmdd1,
to_char(sysdate,'MM')||'월'||to_char(sysdate,'DD')||'일' as mmdd2
FROM dual;

SELECT
EXTRACT(YEAR FROM SYSDATE),
EXTRACT(MONTH FROM SYSDATE),
EXTRACT(DAY FROM SYSDATE)
FROM DUAL;
SELECT HIREDATE, EXTRACT(YEAR FROM HIREDATE) FROM EMP;


-- 밀리세컨 심화 반복하려고
SELECT TO_CHAR(SYSTIMESTAMP,'FF9') FROM DUAL;
SELECT TO_CHAR(SYSTIMESTAMP,'FF9') FROM EMP;
SELECT TO_CHAR(SYSTIMESTAMP,'FF9') FROM EMP
UNION ALL
SELECT TO_CHAR(SYSTIMESTAMP,'FF9') FROM EMP
UNION ALL
SELECT TO_CHAR(SYSTIMESTAMP,'FF9') FROM EMP;


DESC EMP;
--단잃행 변환 함수
SELECT SYSDATE,
TO_CHAR(SYSDATE,'YEAR'),TO_CHAR(SYSDATE,'Year'),
TO_CHAR(SYSDATE,'YYYY'),TO_CHAR(SYSDATE,'YY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'MONTH'),TO_CHAR(SYSDATE,'MON'), 
TO_CHAR(SYSDATE,'Mon'),TO_CHAR(SYSDATE,'mon'),
TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'mm') FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE,'DAY'), TO_CHAR(SYSDATE,'Day'),
TO_CHAR(SYSDATE,'DY'), TO_CHAR(SYSDATE,'dy'),
TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'dd')
FROM DUAL; 
-- // MONTH:9자, MON:3자
SELECT 123456, TO_CHAR(123456,'999999'), LENGTH(TO_CHAR(123456,'999999')),
LENGTH(TO_CHAR(123456,'fm999999')) 
FROM DUAL;
SELECT 123456, TO_CHAR(123456,'000000'), TO_CHAR(12,'00'),LENGTH(TO_CHAR(12,'00')),LENGTH(TO_CHAR(123456,'000000'))  FROM DUAL;
SELECT 123456, TRIM(TO_CHAR(123456,'999999')) FROM DUAL;
SELECT 123456, LENGTH(TRIM(TO_CHAR(123456,'999999'))),LENGTH(TO_CHAR(123456,'999999')),TO_CHAR(123456,'999999'),LENGTH(TO_CHAR(123456,'fm999999')) FROM DUAL;
-- // fm: remove padded blanks 

SELECT TO_CHAR(12345*123.45,'999,999.99'),TO_CHAR(12345*123.45,'99,999,999.99') FROM DUAL; 
--//?

SELECT TO_CHAR(SAL,'$999,999'), REPLACE(TO_CHAR(SAL,'$999,999,999'),' ','?'),
 TO_CHAR(SAL,'L999,999,999'), TO_CHAR(SAL,'999,999L'),TO_CHAR(SAL,'fm999,999L')
FROM EMP;

SELECT 0012345600,TO_CHAR(00123456,'999999999'),TO_CHAR(00123456,'000000000') FROM DUAL;
SELECT 0012345600,TO_CHAR(00123456,'999999999'),TO_CHAR(00123456,'000000000') FROM DUAL;

-- 그룹행 변환함수
SELECT MIN(ENAME),MAX(ENAME),MIN(SAL),MAX(SAL),MIN(HIREDATE),MAX(HIREDATE) FROM EMP;
--// ENAME:문자, SAL:숫자,HIREDATE:날짜
--⑨ 
SELECT COUNT(*),COUNT(EMPNO),COUNT(MGR),COUNT(COMM) FROM EMP;
--⑩ 
SELECT COUNT(JOB),COUNT(ALL JOB),COUNT(DISTINCT JOB),SUM(SAL),SUM(DISTINCT SAL)
FROM EMP;
--⑪ 
SELECT COUNT(*), SUM(COMM), SUM(COMM)/COUNT(*),AVG(COMM),SUM(COMM)/COUNT(COMM)
FROM EMP;
--// 그룹행함수 와 NULL 그리고 NVL , 효율적인 계산방안은 ?
SELECT COUNT(*), SUM(COMM), SUM(NVL(COMM,0))/(COUNT(*)-COUNT(NVL(COMM,0))),AVG(COMM),SUM(COMM)/COUNT(COMM)
FROM EMP;
--⑫ 
SELECT SAL,COMM FROM EMP;
--⑬ 
SELECT SUM(NVL(COMM,0)) AS SUM_COMM1,
 SUM(COMM) AS SUM_COMM2,
 NVL(SUM(COMM),0) AS SUM_COMM3
FROM EMP
