ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';
SELECT ename,sysdate,hiredate FROM emp;
SELECT SYSDATE FROM DUAL;

SELECT sysdate,round(sysdate+60,'YEAR'),round(sysdate,'MONTH'),round(sysdate,'DAY'),round(sysdate)
FROM dual;
-- 과제 1
/*
EXTRACT 함수의 결과 데이터 타입이 무엇인지 오라클 매뉴얼을 검색하여 설명 하십시요 
오라클 메뉴얼에서 EXTRACT를 찾아서 이해하고 설명해기


*/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD:HHMISS') FROM DUAL;
SELECT TO_CHAR(SYStimestamp,'YYYYMMDD:HHMISS') FROM DUAL;

SELECT
EXTRACT(YEAR FROM SYSDATE), 
EXTRACT(MONTH FROM SYSDATE), 
EXTRACT(DAY FROM SYSDATE),
EXTRACT(HOUR FROM SYSTIMESTAMP),
EXTRACT(MINUTE FROM SYSTIMESTAMP),
EXTRACT(SECOND FROM SYSTIMESTAMP),
EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP),
EXTRACT(TIMEZONE_MINUTE FROM SYSTIMESTAMP),
EXTRACT(TIMEZONE_REGION FROM SYSTIMESTAMP),
EXTRACT(TIMEZONE_ABBR FROM SYSTIMESTAMP)
FROM DUAL;

SELECT
EXTRACT(YEAR FROM SYSDATE),
EXTRACT(MONTH FROM SYSDATE),
EXTRACT(DAY FROM SYSDATE),
EXTRACT(timezone_HOUR FROM SYSTIMESTAMP)
FROM DUAL;
/*
,EXTRACT(TIMEZONE_HOUR FROM SYSTIMESTAMP) AS 타임존 아워
,EXTRACT(TIMEZONE_MINUTE FROM SYSTIMESTAMP) AS 타임존 미닛
,EXTRACT(TIMEZONE_REGION FROM SYSTIMESTAMP) AS 타임존의 지역
,EXTRACT(TIMEZONE_ABBR FROM SYSTIMESTAMP) AS 타임존 지역에 대한 약어
-- SYSDATE에서 시간,분,초 추출하려면 에러 발생 SYSDATE는 DATE형 시간이 없을수도있다?
--EXTRACT(MINUTE FROM SYSDATE)
--EXTRACT(SECOND FROM SYSDATE)
*/
SELECT HIREDATE, EXTRACT(YEAR FROM HIREDATE) FROM EMP;

-- 과제 2
/*
날짜 포맷을 조사하여 암기 후 설명
*/
ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE,'PM') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH12') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH24') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MI') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'SSSS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'SSSSS') FROM DUAL;
select to_char(systimestamp, 'YYYY-MM-DD HH24:MI:SSFF3') from dual;
SELECT TO_CHAR(SYSDATE,'D') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'d') FROM DUAL;
--SELECT TO_CHAR(TO_DATE ('27-OCT-00')('20-05-08','DDD')) FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DDD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'dd') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'ddd') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'day') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYYMMDD- FM -HH24MISS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MM') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MON') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'mon') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MONTH') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'month') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'Y') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'y') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'RRRR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'RR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'Year') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'year') FROM DUAL;

SELECT TRIM(TO_CHAR(123456,'999999')) FROM DUAL;
SELECT 123456, TO_CHAR(123456,'999999'), LENGTH(TO_CHAR(123456,'999999')),
LENGTH(TO_CHAR(123456,'fm999999')) 
FROM DUAL;
SELECT TO_CHAR(12345, '00000000') FROM DUAL;
SELECT LENGTH(TO_CHAR(12345, '99999999')) FROM DUAL;
SELECT LENGTH(TO_CHAR(12345, '00000000')) FROM DUAL;
SELECT 123456, TO_CHAR(123456,'000000'), TO_CHAR(12,'00'),LENGTH(TO_CHAR(12,'00')),LENGTH(TO_CHAR(123456,'000000'))  FROM DUAL;
SELECT 123456, TRIM(TO_CHAR(123456,'999999')) FROM DUAL;
SELECT 123456, LENGTH(TRIM(TO_CHAR(123456,'999999'))),LENGTH(TO_CHAR(123456,'999999')),TO_CHAR(123456,'999999'),LENGTH(TO_CHAR(123456,'fm999999')) FROM DUAL;
-- // fm: remove padded blanks 

-- 과제 3
/*
아래 SQL을 참고하여 
해당월의 마지막 법정 영업일자를 구하는 SQL을 작성 하십시요(법정 영업일은 월~금요일) 

SELECT  TO_CHAR(SYSDATE,'DDD'),
         TO_CHAR(SYSDATE,'DD'),
         TO_CHAR(SYSDATE,'D') 
   FROM  DUAL; 

   SELECT  LAST_DAY(SYSDATE) FROM DUAL;
   NOT IN(1,7)
*/
SELECT 
    CASE WHEN TO_CHAR(LAST_DAY(SYSDATE),'DAY') = '일요일' THEN LAST_DAY(SYSDATE)-2  
         WHEN TO_CHAR(LAST_DAY(SYSDATE),'DAY') = '토요일' THEN LAST_DAY(SYSDATE)-1 
         ELSE LAST_DAY(SYSDATE)
    END AS 영업일     
FROM DUAL;
SELECT 
    CASE WHEN TO_CHAR(LAST_DAY(SYSDATE),'D') = '1' THEN LAST_DAY(SYSDATE)-2  
         WHEN TO_CHAR(LAST_DAY(SYSDATE),'D') = '7' THEN LAST_DAY(SYSDATE)-1 
         ELSE LAST_DAY(SYSDATE)
    END AS 영업일     
FROM DUAL;


SELECT 
    CASE WHEN TO_CHAR(TO_DATE('20-04-30','YY-MM-DD'),'DAY') = '일요일' THEN TO_DATE('20-04-30','YY-MM-DD')-2  
         WHEN TO_CHAR(TO_DATE('20-04-30','YY-MM-DD'),'DAY') = '토요일' THEN TO_DATE('20-04-30','YY-MM-DD')-1 
         ELSE TO_DATE('20-04-30','YY-MM-DD')
    END AS 영업일 
FROM DUAL;

SELECT TO_DATE('20-04-30','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('20-04-30','YY/MM/DD') FROM DUAL;