SELECT 300+400,300/0 FROM DUAL;
-- 제수가 0 입니다

SELECT 300+400, 300+NULL, 300/NULL FROM DUAL;
-- NULL 포함 연산은 NULL

SELECT ENAME,SAL,COMM,COMM+SAL*0.3 AS BONUS FROM EMP;
SELECT ENAME,SAL,COMM,NVL(COMM,0)+ SAL*0.3 AS BONUS FROM EMP;
-- COMM에 NULL이 있어서 NULL을 무시하는 함수 NVL사용

SELECT EMPNO, SAL, COMM FROM EMP;
-- 컬럼 관찰
SELECT ENAME, SAL, COMM FROM EMP WHERE SAL > 1000;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > -1;
-- COMM에 NULL 있는 경우 NULL 빼고 볼라고
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM = NULL;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM <> NULL;
-- NULL 은 비교 연산자 안먹음
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM IS NULL;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM IS NOT NULL;
-- NULL의 경우 NULL 만의 연산자가 있음
SELECT ENAME,length(ENAME),COMM,length(to_char(COMM)) FROM EMP;
-- 명시적 형변환 컨버팅?
SELECT SAL-EMPNO,abs(SAL-EMPNO),abs(SAL-COMM)+100 FROM EMP; 
SELECT concat(ENAME||' is ',COMM),nvl(COMM,-1),decode(COMM,null,-999,COMM) FROM EMP;
-- 널 무시하는 함스들

-- 과제 1
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD-HH24:MI:SSSSS')FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD-HH24:MI:SS')FROM DUAL;
select systimestamp from dual;
select to_char(systimestamp, 'YYYY-MM-DD HH:MI:SSFF') from dual;
select to_char(systimestamp, 'YYYY-MM-DD HH:MI:SSFF3') from dual;
select to_char(systimestamp, 'YYYY-MM-DD HH:MI:SSFF4') from dual;
select to_char(systimestamp, 'YYYY-MM-DD HH:MI:SSFF5') from dual;

DESC EMP;
SELECT SAL+COMM FROM EMP;
SELECT HIREDATE FROM EMP;
SELECT HIREDATE+1 FROM EMP;
SELECT HIREDATE-1 FROM EMP;
SELECT HIREDATE*10 FROM EMP;
SELECT HIREDATE/10 FROM EMP;

SELECT EMPNO, SAL, COMM FROM EMP;

SELECT COMM, LENGTH(COMM) FROM EMP;

SELECT SUM(COMM),AVG(COMM),COUNT(*),COUNT(COMM) FROM EMP;

SELECT COUNT(*) FROM SCOTT.EMP  WHERE EMPNO = EMPNO;
SELECT COUNT(*) FROM SCOTT.EMP  WHERE MGR = MGR;
SELECT COUNT(*) FROM SCOTT.EMP  WHERE COMM = COMM;
DESC EMP;
SELECT EMPNO,COMM FROM EMP ORDER BY COMM ASC;
SELECT EMPNO,COMM FROM EMP ORDER BY COMM DESC;

SELECT DISTINCT COMM FROM EMP;
SELECT COUNT(DISTINCT COMM) FROM EMP;
SELECT DISTINCT JOB FROM EMP;

SELECT DISTINCT JOB
FROM EMP
ORDER BY JOB;
SELECT UNIQUE JOB
FROM EMP;

SELECT SAL FROM EMP;

SELECT ROUND(DBMS_RANDOM.VALUE(0,21)) AS PRISENTER FROM DUAL;

SELECT DEPTNO,ENAME,JOB,SAL,TRUNC(DECODE(DEPTNO,10,SAL*0.03,20,SAL*01,SAL*0.01))AS BONUS FROM EMP ORDER BY DEPTNO ASC,BONUS DESC;

SELECT GREATEST(3000,1500,2100,5000),LEAST(3000,1500,2100,5000) FROM DUAL ; 

SELECT DEPTNO, ENAME, SAL, DECODE(GREATEST(SAL,5000),SAL,'HIGH', DECODE(GREATEST(SAL,2500),SAL,'MID','LOW')) FROM EMP ORDER BY DEPTNO; 

SELECT ROWNUM,ENAME,DEPTNO,SAL FROM EMP;
SELECT ROWNUM,ENAME,DEPTNO,SAL FROM EMP ORDER BY DEPTNO,SAL;
SELECT ROWNUM,ENAME,DEPTNO,SAL FROM EMP WHERE  DEPTNO IN (10,20) ORDER BY DEPTNO,SAL; 
SELECT ENAME,DEPTNO,SAL FROM EMP ORDER BY ROWNUM;
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE ROWNUM = 1;
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE ROWNUM = 5;
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE ROWNUM > 5;
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE ROWNUM <= 5; 
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE ROWNUM < 5; 

SELECT  DEPTNO,ENAME,SAL  
FROM EMP  
WHERE  ROWNUM <= 5 
ORDER  BY SAL DESC ;

SELECT DEPTNO,ENAME,SAL FROM EMP ORDER  BY SAL DESC;

SELECT ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO = 10 AND SAL > 2000; 
SELECT ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO = 10 OR  SAL > 2000; 
SELECT ENAME,JOB,SAL,DEPTNO FROM EMP
WHERE DEPTNO = 10 AND SAL > 2000 OR JOB = 'CLERK';

SELECT EMPNO,ENAME,HIREDATE,SAL FROM EMP WHERE SAL between 2000 and 1000;

SELECT EMPNO,HIREDATE,SAL FROM EMP WHERE HIREDATE between '1981/02/20' and '1982/12/09'; 
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('81/02/20','yy/mm/dd') and to_date('82/12/09','yy/mm/dd'); 
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('1981/02/20','YYyy/mm/dd') and to_date('1982/12/09','YYyy/mm/dd'); 
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('81/02/20','yy/mm/dd') and to_date('82/12/09','yy/mm/dd'); 
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('81/02/20','yy/mm/dd') and to_date('82/12/09','yy/mm/dd'); 

SELECT ENAME,HIREDATE,SAL FROM EMP WHERE  HIREDATE between to_date('81/02/20','rr/mm/dd') and to_date('82/12/09','rr/mm/dd');
SELECT * FROM SALGRADE  WHERE  3000 BETWEEN LOSAL AND HISAL; 

SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO IN (7369,7369,7654); 
SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO = 7369 or EMPNO = 7521 or EMPNO=7654; 
SELECT EMPNO,ENAME,JOB FROM EMP WHERE JOB in ('CLERK','MANAGER');  SELECT EMPNO,ENAME,JOB FROM EMP WHERE JOB in ('clerk','manager'); 
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE HIREDATE IN ('81/05/01','81/02/20'); 
SELECT EMPNO,ENAME,JOB,DEPTNO FROM EMP  WHERE (JOB,DEPTNO) in (('MANAGER',20),('CLERK',20)); . SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO IN (7369,7369,7654); 
SELECT DEPTNO, ENAME, JOB FROM SCOTT.EMP  WHERE DEPTNO IN (SELECT DEPTNO FROM SCOTT.DEPT WHERE LOC IN ('NEWYORK','CHICAGO')); 
SELECT ENAME FROM EMP WHERE ENAME like 'A%'; 
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO = '7369';
 SELECT ENAME FROM EMP WHERE ENAME like 'A%'; 
 SELECT ENAME FROM EMP WHERE ENAME like '_A%'; 
 SELECT ENAME FROM EMP WHERE ENAME like '%L%E%'; 
 SELECT ENAME FROM EMP WHERE ENAME like '%LE%'; 
 SELECT ENAME FROM EMP WHERE ENAME like '%A%'; 
 SELECT ENAME FROM EMP WHERE ENAME NOT like '%A%'; 
 SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE like '81%';   
 SELECT ENAME,SAL FROM EMP WHERE SAL like 2%; 
 SELECT ENAME,SAL FROM EMP WHERE SAL like '2%';   