ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';

SELECT 123456, TO_CHAR(123456,'999999'), 
LENGTH(TO_CHAR(123456,'999999')), LENGTH(TO_CHAR(123456,'fm999999')) from dual;

SELECT COUNT(*), SUM(COMM), SUM(COMM)/COUNT(*),AVG(COMM),SUM(COMM)/COUNT(COMM)
FROM EMP;

SELECT SUM(NVL(COMM,0)) AS SUM_COMM1,
 SUM(COMM) AS SUM_COMM2,
 NVL(SUM(COMM),0) AS SUM_COMM3
FROM EMP;


SELECT SYSDATE,
TO_CHAR(SYSDATE,'YEAR'),TO_CHAR(SYSDATE,'Year'),
TO_CHAR(SYSDATE,'YYYY'),TO_CHAR(SYSDATE,'YY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'MONTH'),TO_CHAR(SYSDATE,'MON'), 
TO_CHAR(SYSDATE,'Mon'),TO_CHAR(SYSDATE,'mon'),
TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'mm') FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE,'DAY'), TO_CHAR(SYSDATE,'Day'),
TO_CHAR(SYSDATE,'DY'), TO_CHAR(SYSDATE,'dy'),
TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'dd')
FROM DUAL; 

SELECT 123456, TO_CHAR(123456,'999999'), LENGTH(TO_CHAR(123456,'999999')),
LENGTH(TO_CHAR(123456,'fm999999'))
FROM DUAL;

SELECT TO_CHAR(12345*123.45,'999,999.99'),TO_CHAR(12345*123.45,'99,999,999.99') FROM DUAL;

SELECT TO_CHAR(SAL,'$999,999'), REPLACE(TO_CHAR(SAL,'$999,999'),' ','?'),
 TO_CHAR(SAL,'L999,999'), TO_CHAR(SAL,'999,999L'),TO_CHAR(SAL,'fm999,999L')
FROM EMP;

SELECT 0012345600,TO_CHAR(00123456,'999999999'),TO_CHAR(00123456,'000000000') FROM DUAL;

-- 그룹행 함수
SELECT MIN(ENAME),MAX(ENAME),MIN(SAL),MAX(SAL),MIN(HIREDATE),MAX(HIREDATE) FROM EMP;
// ENAME:문자, SAL:숫자,HIREDATE:날짜

SELECT COUNT(*),COUNT(EMPNO),COUNT(MGR),COUNT(COMM) FROM EMP;

 SELECT COUNT(JOB),COUNT(ALL JOB),COUNT(DISTINCT JOB),SUM(SAL),SUM(DISTINCT SAL)
FROM EMP;

SELECT COUNT(*), SUM(COMM), SUM(COMM)/COUNT(*),AVG(COMM),SUM(COMM)/COUNT(COMM)
FROM EMP;

--그룹행함수 와 NULL 그리고 NVL , 효율적인 계산방안은 ?
SELECT SAL,COMM FROM EMP;

SELECT SUM(NVL(COMM,0)) AS SUM_COMM1,
 SUM(COMM) AS SUM_COMM2,
 NVL(SUM(COMM),0) AS SUM_COMM3
FROM EMP;

-- GRUOP BY 함수

SELECT DEPTNO,COUNT(*),SUM(SAL),AVG(SAL) FROM EMP
GROUP BY DEPTNO;

SELECT JOB, COUNT(*), AVG(SAL) FROM EMP
GROUP BY JOB;
-- 정렬된 결과를 얻기 위해서는 오더바이 맨마지막에
SELECT DEPTNO,COUNT(*),SUM(SAL),AVG(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;
-- NULL도 그룹핑 대상이 되는지? 된다
SELECT COMM,COUNT(*) FROM EMP
GROUP BY COMM;

SELECT DEPTNO,
COUNT(*) AS CNT_DEPT,
SUM(SAL) AS SUM_SAL,
ROUND(AVG(SAL),0) AS AVG_SAL
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO,SUM_SAL;

SELECT DEPTNO,COUNT(*),SUM(SAL),AVG(SAL) FROM EMP
WHERE DEPTNO IN (10,20)
GROUP BY DEPTNO
HAVING SUM(SAL) > 9000
ORDER BY SUM(SAL);


-- SQL 스크립트화!! 사용자 정의 프로시져 ? 
SET SERVEROUTPUT ON;

EXECUTE SELECTION;

-- 시퀀스!!!!!!!!!!!!!!!!!!

CREATE SEQUENCE SCOTT.ORDER_SEQ16
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999
MINVALUE 1
NOCYCLE
CACHE 30;


SELECT ORDER_SEQ16.CURRVAL FROM DUAL;

SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
 SELECT ORDER_SEQ16.CURRVAL FROM DUAL;
SELECT ORDER_SEQ16.CURRVAL FROM DUAL;
 ROLLBACK;
 
 SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;

SELECT EMPNO,ENAME,ORDER_SEQ16.NEXTVAL FROM EMP;

ALTER SESSION SET NLS_DATE_FORMAT = ‘YYYY-MM-DD:HH24:MI:SS’; 

--6
SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
--8
SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
--10
SELECT ORDER_SEQ16.CURRVAL FROM DUAL;

--13
SELECT ORDER_SEQ16.CURRVAL FROM DUAL;


ALTER SESSION SET NLS_DATE_FORMAT = ‘YYYY-MM-DD:HH24:MI:SS’; 
--7
SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
--9
SELECT ORDER_SEQ16.NEXTVAL FROM DUAL;
--11
SELECT ORDER_SEQ16.CURRVAL FROM DUAL;
--12
SELECT ORDER_SEQ16.CURRVAL FROM DUAL;

SELECT * FROM v$session;

CREATE SEQUENCE SCOTT.ORDER_SEQ16_2
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999999
MINVALUE 1
NOCYCLE
CACHE 30;

SELECT * FROM TAB;

