SELECT DEPTNO FROM EMP;

SELECT 
    SUM(DECODE(DEPTNO,10,COUNT(DEPTNO),0))"10번 부서",
    SUM(DECODE(DEPTNO,20,COUNT(DEPTNO),0))"20번 부서",
    SUM(DECODE(DEPTNO,30,COUNT(DEPTNO),0))"30번 부서"
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO,
    DECODE(DEPTNO,10,COUNT(DEPTNO))"10번 부서",
    DECODE(DEPTNO,20,COUNT(DEPTNO))"20번 부서",
    DECODE(DEPTNO,30,COUNT(DEPTNO))"30번 부서"
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO FROM EMP;


SELECT DEPTNO, 
    DECODE(DEPTNO,10,COUNT(DEPTNO),NULL)"10번 부서",
    DECODE(DEPTNO,20,COUNT(DEPTNO),NULL)"20번 부서",
    DECODE(DEPTNO,30,COUNT(DEPTNO),NULL)"30번 부서"
    
FROM EMP


SELECT DEPTNO, 
    DECODE(DEPTNO,10,COUNT(DEPTNO),NULL)"10번 부서",
    DECODE(DEPTNO,20,COUNT(DEPTNO),NULL)"20번 부서",
    DECODE(DEPTNO,30,COUNT(DEPTNO),NULL)"30번 부서"
    
FROM EMP;

SELECT 
        SUM(COUNT(CASE WHEN DEPTNO = 10 THEN 0 END)) "10번부서",
        SUM(COUNT(CASE WHEN DEPTNO = 20 THEN 0 END)) "20번부서",
        SUM(COUNT(CASE WHEN DEPTNO = 30 THEN 0 END)) "30번부서"
FROM EMP
GROUP BY DEPTNO;

SELECT COUNT(DEPTNO) FROM EMP;