--2
SELECT * FROM SYSTEM16;
SELECT * FROM RESOURCE_USAGE16;

SELECT S.SYSTEM_ID, S.SYSTEM_NAME, R.RESOURCE_NAME
FROM SYSTEM16 S, RESOURCE_USAGE16 R
WHERE S.SYSTEM_ID = R.SYSTEM_ID;

SELECT S.SYSTEM_ID,S.SYSTEM_NAME,R.RESOURCE_NAME
FROM SYSTEM16 S,RESOURCE_USAGE16 R
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+);

SELECT S.SYSTEM_ID,S.SYSTEM_NAME, 
    MAX(DECODE(R.RESOURCE_NAME,'FTP','사용','미사용'))"FTP",
    MAX(DECODE(R.RESOURCE_NAME,'TELNET','사용','미사용'))"TELNET",
    MAX(DECODE(R.RESOURCE_NAME,'EMAIL','사용','미사용'))"EMAIL"
FROM SYSTEM16 S, RESOURCE_USAGE16 R
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+)
GROUP BY S.SYSTEM_ID,S.SYSTEM_NAME
ORDER BY S.SYSTEM_ID ASC;


-- 3
SELECT SAL,ENAME FROM EMP ORDER BY SAL DESC;

SELECT A.DEPTNO, A.ENAME, A.JOB, A.SAL, COUNT(B.ENAME)+1 AS HIGHSAL
FROM EMP A, EMP B
WHERE A.DEPTNO = B.DEPTNO(+) AND A.SAL < B.SAL(+) 
GROUP BY A.DEPTNO, A.JOB, A.ENAME, A.SAL
ORDER BY A.DEPTNO, A.SAL DESC;

--4
-- RNAK는 값 같아도 순위 다름
SELECT DEPTNO, ENAME,JOB,SAL,RANK() OVER(ORDER BY SAL DESC)"급여순위"
FROM EMP;
--DENSE_RANK 는 동일값은 순위 같게
SELECT DEPTNO, ENAME,JOB,SAL,DENSE_RANK() OVER(ORDER BY SAL DESC)"급여순위"
FROM EMP;

SELECT DEPTNO, ENAME, JOB, SAL,RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) "급여순위"
FROM EMP; 

SELECT DEPTNO, ENAME, JOB, SAL,DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) "급여순위"
FROM EMP; 
--5

SELECT DEPTNO,ENAME,SAL,
    TO_CHAR(ROUND(SAL/SUM(SAL)*100,2),'99.99')||'%' AS SAL_RATE
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
ORDER BY SAL_RATE;
-- #####나오는 것은 '99.99'랑 데이터랑 안맞음
SELECT DEPTNO,ENAME,SAL,
    (ROUND(SAL/SUM(SAL)*100,2),'99.99')||'%' AS SAL_RATE
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
ORDER BY SAL_RATE;
-- SUM(SAL) 조회하면 SUM이 안먹음... 그럼 SUM(SAL을 구해서 MQ에 주자)
SELECT DEPTNO, ENAME, SAL, 
 TO_CHAR(ROUND(SAL/IV.SUM_SAL*100,2),'99.99')||'%' AS SAL_RATE
FROM EMP, (SELECT SUM(SAL) AS SUM_SAL FROM EMP) IV
ORDER BY SAL_RATE;


SELECT deptno, ename, job, sal, 
       to_char(ROUND(sal/sum_sal * 100, 2), '99.99') || '%' as sal_rate 
FROM EMP , (select sum(sal) as sum_sal from emp)
ORDER BY SAL_RATE;
-- IV예제
SELECT DEPTNO, ENAME,EMP.JOB,SAL,IV.AVG_SAL
FROM EMP, (SELECT JOB,ROUND(AVG(SAL)) AS AVG_SAL FROM EMP GROUP BY JOB ) IV
WHERE EMP.JOB = IV.JOB AND SAL > IV.AVG_SAL
ORDER BY DEPTNO ,SAL DESC
