@@C:\Users\HP\Desktop\myGit\SQL\demobld.sql
select * from tab;

@@C:\Users\HP\Desktop\myGit\SQL\T_CONS.sql

DROP TABLE   DA16.CUSTOMER;           
CREATE TABLE   DA16.CUSTOMER(
	ID VARCHAR2(8) NOT NULL,
	PWD VARCHAR2(8) CONSTRAINT CUSTOMER_PWD_NN NOT NULL, 
	NAME VARCHAR2(20), --이름 
	SEX CHAR(1), --성별[M|F] M:MALE F: FEMALE
	AGE NUMBER(3)--나이
) ;

desc CUSTOMER;
INSERT INTO CUSTOMER(ID,PWD,NAME,SEX,AGE)VALUES('XAMAN','OK','KANG','M',21);

SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;

CREATE SEQUENCE Bank_number_tag
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999 --| NOMAXVALUE]
    MINVALUE 001 --| NOMINVALUE]
    CYCLE --| NOCYCLE]
    CACHE 100; --| NOCACHE]
    
CREATE TABLE MEMBERINFO(
    NUMBER_TAG NUMBER PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL
);

SELECT Bank_number_tag.NEXTVAL FROM DUAL;

INSERT INTO MEMBERINFO VALUES(Bank_number_tag.NEXTVAL, 'LEE');
INSERT INTO MEMBERINFO VALUES(Bank_number_tag.NEXTVAL, 'PARK');

SELECT Bank_number_tag.CURRVAL FROM MEMBERINFO;
SELECT * FROM MEMBERINFO;

@@C:\Users\HP\Desktop\myGit\SQL\T_CONS2.SQL;
INSERT INTO CUSTOMER2(ID,PWD,NAME,SEX,AGE) VALUES('XMAN','NO','KIM','M',20);
INSERT INTO CUSTOMER2(ID,PWD,NAME,SEX,AGE) VALUES('XMAN','NO','KIM','M',99);

UPDATE CUSTOMER2 SET AGE = AGE + 1;
SELECT AGE FROM CUSTOMER2;

@@C:\Users\HP\Desktop\myGit\SQL\T_CONS3.SQL;

INSERT INTO CUSTOMER3(ID,PWD,NAME,MOBILE,AGE) VALUES('XMAN','OK','KANG','010-2121',20);
SELECT * FROM CUSTOMER3;
ALTER TABLE CUSTOMER3 ADD CONSTRAINT CUSTOMER3_NAME_SEX_UK UNIQUE(NAME,SEX);
ALTER TABLE CUSTOMER3 MODIFY(NAME NOT NULL);

SELECT INDEX_NAME,INDEX_TYPE,UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'CUSTOMER3';

SELECT * FROM TAB;
@@C:\Users\HP\Desktop\myGit\SQL\ORDER_TBL.SQL;
DROP TABLE SCOTT.ORDERS;

CREATE TABLE SCOTT.ORDERS --ORDER 테이블명을 사용할수 없는 이유는?
	( ORDER_ID NUMBER(12) CONSTRAINT ORDER_ID_PK PRIMARY KEY,
	  ORDER_DATE DATE DEFAULT SYSDATE CONSTRAINT ORDER_DATE_NN NOT NULL,
	  ORDER_MODE VARCHAR2(8) CONSTRAINT ORDER_MODE_CHK CHECK(ORDER_MODE IN ('direct','online')),
	  CUSTOMER_ID NUMBER(6) CONSTRAINT ORDER_CUSTOMER_ID_NN NOT NULL,
	  ORDER_STATUS NUMBER(2), -- 0: 주문중 , 1: 주문완료, 2: 취소 , 3: 발송 4: 수취
	  SALES_ID NUMBER(6), -- 판매사원번호
  	  CONSTRAINT ORDER_SALES_ID_FK FOREIGN KEY(SALES_ID) REFERENCES SCOTT.EMP(EMPNO)
);
DESC SCOTT.ORDERS