<<MAIN_BLK>>

DECLARE
	V_DNAME	VARCHAR2(14);
	V_DEPTNO	NUMBER(2);
	V_LOC		VARCHAR2(13);
BEGIN
	V_DEPTNO := 77;
	V_DNAME := 'GLOBAL_PART';
	V_LOC := 'Main_Blk';

	<<LOCAL_BLOCK_1>>
	DECLARE
		V_DNAME	VARCHAR2(14);
		V_DEPTNO	NUMBER(2);
	BEGIN
		V_DEPTNO := 88;
		V_DNAME := 'GLOBAL_PART_1';
		V_LOC := 'Main_Blk1';
		INSERT INTO  DEPT VALUES(V_DEPTNO, MAIN_BLK.V_DNAME,V_LOC);
	END LOCAL_BLOCK_1;

	<<LOCAL_BLOCK_2>>
	DECLARE
		V_DNAME	VARCHAR2(14);
		V_DEPTNO	NUMBER(2);
	BEGIN
		V_DEPTNO := 99;
		V_DNAME := 'GLOBAL_PART_2';
		V_LOC := 'Main_Blk2';
		INSERT INTO  DEPT VALUES(V_DEPTNO, V_DNAME, V_LOC);
	END;

	INSERT INTO DEPT VALUES(V_DEPTNO, V_DNAME, V_LOC);
END MAIN_BLK;
/