DA01/DA01
SELECT*FROM TAB;
SELECT*FROM EMP;
SELECT*FROM DA16.EMP;
ALTER USER DA16 IDENTIFIED BY 1005;
SHOW USER;
SELECT * FROM V$SESSION
WHERE USERNAME LIKE 'DA%'
ORDER BY USERNAME;
/* 
은행에서 보안에 문제가 나면 거의 내부 소행이다.
*/
