SELECT * FROM EMP
WHERE EMPNO = &V_EMPNO; -- 1회성 변수

SELECT * FROM EMP
WHERE EMPNO = &&V_DEPTNO; -- 세션 변수

VARIABLE
DEFINE
UNDEFINE V_EMPNO;

DECLARE
	CURSOR CUR_EMP(P_DEPTNO IN NUMBER) IS
		SELECT ENAME,JOB,SAL,COMM FROM EMP WHERE DEPTNO = P_DEPTNO;
	V_DEPTNO 	DEPT.DEPTNO%TYPE;
BEGIN
	--V_DEPTNO := 20;

	FOR R_CUR_EMP IN CUR_EMP(V_DEPTNO)
	LOOP
		INSERT INTO BONUS(ENAME,JOB,SAL,COMM)
			VALUES(R_CUR_EMP.ENAME,R_CUR_EMP.JOB,R_CUR_EMP.SAL,R_CUR_EMP.COMM);
	END LOOP;

	--DBMS_OUTPUT.PUT_LINE('TOTAL '||TO_CHAR(CUR_EMP%ROWCOUNT)||'ROWS PROCESSED');
	COMMIT;
END;
/
SELECT * FROM BONUS;
SELECT * FROM EMP WHERE DEPTNO=20;