@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_1.SQL
SELECT EMPNO,JOB,SAL,COMM FROM EMP WHERE DEPTNO = 10;
SELECT * FROM BONUS;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_ATT_IMP.SQL

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_2.SQL
SET SERVEROUT ON
@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_3.SQL
SELECT * FROM BONUS;
SELECT * FROM EMP WHERE DEPTNO=10;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_4_1.SQL
SELECT * FROM BONUS;
SELECT * FROM EMP WHERE DEPTNO=10;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_4_2.SQL
SELECT * FROM BONUS;
SELECT * FROM EMP WHERE DEPTNO=10;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_5.SQL
SELECT * FROM BONUS;
SELECT * FROM EMP WHERE DEPTNO=20;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_for_update.SQL
SELECT * FROM BONUS;
SELECT TO_CHAR(SYSDATE,'HH24:MI:SS') AS END_TIME FROM DUAL;

