@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_1.SQL
SELECT EMPNO,JOB,SAL,COMM FROM EMP WHERE DEPTNO = 10;
SELECT * FROM BONUS;

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_ATT_IMP.SQL

@@C:\Users\HP\Desktop\myGit\SQL\5_CURSOR_2.SQL