DROP TABLE   DA16.CUSTOMER;           
CREATE TABLE   DA16.CUSTOMER(
	ID VARCHAR2(8) NOT NULL,
	PWD VARCHAR2(8) CONSTRAINT CUSTOMER_PWD_NN NOT NULL, 
	NAME VARCHAR2(20), --이름 
	SEX CHAR(1), --성별[M|F] M:MALE F: FEMALE
	AGE NUMBER(3)--나이
) ;
