DROP TABLE DA16.CUSTOMER2;    
CREATE TABLE DA16.CUSTOMER2(
	ID VARCHAR2(8) NOT NULL,
	PWD VARCHAR2(8) CONSTRAINT    CUSTOMER2_PWD_NN NOT NULL,
	NAME VARCHAR2(20),
	SEX CHAR(1) CONSTRAINT CUSTOMER2_SEX_CK CHECK (SEX IN ('M','F')),
	AGE NUMBER(3) CHECK    ( AGE > 0 AND AGE < 100)
) ;
